export default function randomAlerts() {
    let successMsg = [
        '"Los ordenadores son inútiles. Sólo pueden darte respuestas"-- Pablo Picasso', 
        '"Los ordenadores son como los bikinis. Ahorran a la gente el hacer muchas conjeturas"-- Sam Ewing', 
        '"Es genial trabajar con ordenadores. No discuten, lo recuerdan todo y no se beben tu cerveza"-- Paul Leary', 
        '"La web es como una dominatriz. En todos los sitios que voy me encuentro pequeños botones ordenándome que me someta"-- Nytwind ', 
        '"R2D2, ¿te lo dijo la computadora central de la ciudad? ¡R2D2, sabes bien que no debes confiar en una computadora extraña!-- C3PO',
        '"Nunca confíes en un ordenador que no puedas lanzar por una ventana" -- Steve Wozniak ',
        '"Hay dos maneras de diseñar software: una es hacerlo tan simple que sea obvia su falta de deficiencias, y la otra es hacerlo tan complejo que no haya deficiencias obvias"-- C.A.R. Hoare',
        '"Hay una antigua historia sobre una persona que quería que su ordenador fuese tan fácil de utilizar como su teléfono. Estos deseos se han hecho realidad, ya no sé cómo usar mi teléfono"-- Bjarne Stroustrup',
        '"La programación es una carrera entre los desarrolladores, intentando construir mayores y mejores programas a prueba de idiotas, y el universo, intentanto producir mayores y mejores idiotas. Por ahora va ganando el Universo"-- Rich Cook',
        '"La mayoría de ustedes están familiarizados con las virtudes del programador. Son tres, por supusto: pereza, impaciencia y orgullo desmedido"-- Larry Wall',
        '"El problema que hay con los programadores es que nunca puedes contar lo que un programador está haciendo hasta que es demasiado tarde"-- Seymour Cray',
        '"Esto es lo que ocurre con la gente que piensa que odia los ordenadores. Lo que realmente odia es a los malditos programadores"-- Larry Niven',
        '"Durante mucho tiempo no entendía cómo algo tan caro y puntero podía ser tan inútil. Y entonces me vino a la mente que un ordenador es una máquina estúpida con la habilidad de hacer cosas increíblemente inteligentes, mientras que los programadores son inteligentes personas con la habilidad de hacer cosas estúpidas. Son, en resumen, una pareja perfecta"-- Bill Bryson',
        '"Un programador es la persona considerada experta en ser capaz de sacar, después de innumerables tecleos, una serie infinita de respuestas incomprensibles calculadas con precisión micrométrica a partir de vagas asunciones basadas en discutibles cifras tomadas de documentos inconcluyentes y llevados a cabo con instrumentos de escasa precisión, por personas de fiabilidad dudosa y cuestionable mentalidad con el propósito declarado de molestar y confundiar al desesperado e indefenso departamento que tuvo la mala fortuna de pedir la información en primer lugar"-- IEEE Grid newsmagazine',
        '"No te preocupes si no funciona bien. Si todo estuviera correcto, serías despedido de tu trabajo"-- Ley de Mosher de la Ingeniería del Software',
        '"Lo mejor de los booleanos es que si te equivocas estás a un sólo bit de la solución correcta"-- Anonymous',
        '"PHP es un mal menor perpetrado y creado por amaterus incompetentes, mientras que Perl es un gran e insidioso mal perpetrado por hábiles pero pervertidos profesionales"-- Jon Ribbens',
        '"El uso de COBOL daña la mente. Su enseñanza debería ser considerada como un ataque criminal"-- E. W. Dijkstra',
        '"Es prácticamente imposible enseñar buenos hábitos de programación a estudiantes que hayan sido previamente sometidos a una exposición de BASIC. Como desarrolladores en potencia, están mentalmente mutilados sin esperanza de regeneración"-- E. W. Dijkstra',
        '"Escribir en C o C++ es como utilizar una sierra eléctrica sin ningún tipo de protección"-- Bob Gray',
        '"Bien, Java podría ser un buen ejemplo de cómo debería ser un lenguaje de programación. Sin embargo, las aplicaciones Java son buenos ejemplos de cómo las aplicaciones no deberían ser"-- Pixadel',
        '"Si Java dispusiera de un mecanismo real de recolección de basura, la mayoría de los programas deberían autoeliminarse al ser ejecutados"-- Robert Sewell',
        '"El primer 90% del código corresponde al primer 90% del tiempo de desarrollo. El 10% restante corresponde al otro 90% del desarrollo"-- Tom Cargill',
        '"En software, muy raramente partimos de requisitos con sentido. Incluso teniéndolos, la única medida del éxito que importa es si nuestra solución resuelve la cambiante idea que el cliente tiene de lo que es su problema"-- Jeff Atwood',
        '"Depurar es al menos dos veces más duro que escribir el código por primera vez. Por tanto, si tu escribes el código de la forma más inteligente posible no serás, por definición, lo suficientemente inteligente para depurarlo"-- Brian Kernighan',
        '"Si la depuración es el proceso de eliminar errores, entonces la programación debe ser el proceso de introducirlos"-- Edsger W. Dijkstra',
        '"Hay dos formas de escribir programas sin errores; sólo la tercera funciona"-- Alan J. Perlis',
        '"Si McDonnalds funcionara como una compañía de software, uno de cada cien Big Macs te envenenarían, y la respuesta sería: lo sentimos, aquí tiene un cupón para dos más"-- Mark Minasi',
        '"Codifica siempre como si la persona que finalmente mantendrá tu código fuera un psicópata violento que sabe dónde vives"-- Martin Golding',
        '"Un ordenador te permite cometer más errores y más rápido que cualquier otra invención en la historia de la humanidad, con las posibles excepciones de las pistolas y el tequila"-- Mitch Radcliffe',
        '"Si las cosas siguen así, al hombre se le atrofiarán todas sus extremidades excepto los dedos de pulsar los botones"-- Frank Lloyd Wright',
        ' "Todas las piezas deben unirse sin ser forzadas. Debe recordar que los componentes que está reensamblando fueron desmontados por usted, por lo que si no puede unirlos debe existir una razón. Pero sobre todo, no use un martillo"-- Manual de mantenimiento de IBM, año 1925',
        '"La mayoría de expertos está de acuerdo en que la causa más probable de destrucción del mundo sería por accidente; y aquí es donde entramos nosotros: somos profesionales de la informática, causamos accidentes"-- Nathaniel Borenstein',
        '"Si en una sala llena de diseñadores de software dos de ellos están de acuerdo, eso es una mayoría"-- Bill Curtis',
        '"Una de las cosas más fascinantes de los programadores es que no puedes saber si están trabajando o no sólo con mirarlos. A menudo están sentados aparentemente tomando café o mirando a las nubes. Sin embargo, es posible que estén poniendo en orden todas las ideas individuales y sin relación que pululan por su mente"-- Charles M. Strauss',
        ' "Comentar el código es como limpiar el cuarto de baño; nadie quiere hacerlo, pero el resultado es siempre una experiencia más agradable para uno mismo y sus invitados"-- Ryan Campbell',
        '"Ley de Alzheimer de la programación: si lees un código que escribiste hace más de dos semanas es como si lo vieras por primera vez"-- Via Dan Hurvitz',
        '"La generación de código, como beber alcohol, es bueno si se hace con moderación"-- Alex Lowe',
        '"Programar sin una arquitectura o diseño en mente es como explorar una gruta sólo con una linterna: no sabes dónde estás, dónde has estado ni hacia dónde vas"-- Danny Thorpe',
        '"En dos ocasiones me han preguntado: si pone datos incorrectos en la máquina, ¿saldrán las respuestas correctas?. Soy absolutamente incapaz de hacerme una idea del tipo de confusión de ideas que pueden provocar que alguien haga una pregunta así"-- Charles Babbage',
        '"La gestión manual de bloques de memoria en C es como hacer malabarismos con pastillas de jabón en la ducha de la prisión: todo diversión hasta que cometes un fallo"-- Un usuario anónimo de un foro Usenet',
        '"Algunos desarrolladores cuando se enfrentan a un problema piensan que la solución es usar expresiones regulares. En este momento, ya tienen dos problemas"-- Jamie Zawinski',
        '"No soy de los que piensan que Bill Gates es el diablo. Simplemente sospecho que si Microsoft alguna vez se encontrara con el diablo, no necesitarían un intérprete"-- Nicholas Petreley'
        ]

    alert(successMsg[Math.floor(Math.random() * successMsg.length)]);
    }

